version: "3.5"

services:

  #php server
  php:
    image: mctekk/phalconphp:latest
    volumes:
      - .:/app
      - ../canvas-core:/canvas-core
      - ../canvas-sdk-php:/canvas-sdk-php
      - ../../baka:/baka
    depends_on:
      - 'redis'
      - 'mysql'
    tty: true
    ports:
      - "9000:9000"
    networks:
      - local-network

  swoole:
    build: .
    volumes:
      - .:/app
      - ../canvas-core:/canvas-core
      - ../canvas-sdk-php:/canvas-sdk-php
      - ../../baka:/baka
    depends_on:
      - 'redis'
      - 'mysql'
    tty: true
    ports:
      - "8081:8081"
    networks:
      - local-network

  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    links:
        - php
    volumes:
        - .:/app
        - ./storage/ci/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local-network
      - public-network

  redis:
    image: 'redis:5.0.5-alpine'
    ports: 
      - "6379:6379"
    volumes:
      - 'redis:/data'
    networks:
      - local-network

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - local-network

  elasticsearch: # Elasticsearch Instance
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch-kanvas
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    #command: ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.7.0.0/elasticsearch-sql-6.7.0.0.zip #install sql plugin
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    networks:
      - local-network

  mysql:
    image: mariadb:10.4
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    volumes:
      - "db-data:/var/lib/mysql"
      - "./storage/ci/mysql.cnf:/etc/mysql/conf.d/kanvas.cnf"
    networks:
        - local-network
  
  rabbitmq:
    image: rabbitmq:3.7.16-management
    hostname: "rabbit"
    env_file:
      - '.env'
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "rabbitsvolumns:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - local-network

volumes:
  db-data:
  redis:
  esdata:
  rabbitsvolumns:

networks:
  local-network:
  public-network: